name: Run Notebook (Smoke)

on:
  pull_request:
    paths:
      - 'notebooks/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nbconvert jupyter
      - name: Execute notebook (headless)
        run: |
          jupyter nbconvert --to notebook --execute notebooks/01_train.ipynb \
            --output notebooks/01_train_executed.ipynb \
            --ExecutePreprocessor.timeout=180
